_wandb:
    value:
        cli_version: 0.20.1
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 9
            "2":
                - 1
                - 9
            "3":
                - 7
                - 13
                - 55
                - 66
            "4": 3.8.20
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
