_wandb:
    value:
        cli_version: 0.20.1
        m:
            - "1": q3_l2err
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": val_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": q1_angular_err
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_loss_epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": max_l2err
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": max_angular_err
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": std_max_l2err
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_loss_step
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": median_l2err
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": ave_l2err
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": q1_l2err
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": q2_angular_err
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": ave_max_angular_err
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": test_set_size
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": samples_per_endpoint
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": q2_l2err
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": q3_angular_err
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": ave_angular_err
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": median_angular_err
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": std_max_angular_errs
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": std_l2errs
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": ave_max_l2err
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": std_angular_err
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 9
            "2":
                - 1
                - 9
            "3":
                - 2
                - 7
                - 13
                - 55
                - 66
            "4": 3.8.20
            "5": 0.20.1
            "10":
                - 22
            "12": 0.20.1
            "13": linux-x86_64
